# config/settings.yaml

# app:
#   env: dev
#   host: 127.0.0.1
#   port: 8050
#   dev_reload: true
app:
  name: ${APP_NAME:rs-rraPhrag}
  env: ${APP_ENV:dev}
  host: ${HOST:127.0.0.1}
  port: ${PORT:8050}
  log_level: ${LOG_LEVEL:INFO}

# storage:
#   backend: local
#   root_dir: ${STORAGE_ROOT:-data}
#   tmp_dir: ${STORAGE_TMP:-data/_tmp}
#   allowed_extensions: [".pdf",".txt",".csv",".docx",".xlsx",".xls"]
storage:
  root: ${STORAGE_ROOT:./data}
  series_dirname: series
  # Extensions autorisées pour l'import multi-fichiers
  tmp_dir: ${STORAGE_TMP:./data/_tmp}
  allowed_extensions: ['.pdf', '.txt', '.csv', '.docx', '.xlsx', '.xls']

upload:
  max_size_mb: 50

# neo4j:
#   uri: ${NEO4J_URI:-bolt://localhost:7687}
#   database: ${NEO4J_DATABASE:-neo4j}
#   username: ${NEO4J_USERNAME:-neo4j}
#   password: ${NEO4J_PASSWORD:-}
neo4j:
  uri: ${NEO4J_URI:bolt://localhost:7687}
  database: ${NEO4J_DATABASE:neo4j}
  username: ${NEO4J_USERNAME:neo4j}
  password: ${NEO4J_PASSWORD:neo4j}

# vector:
#   provider: chroma
#   params:
#     persist_dir: data/chroma
vector:
  provider: chroma
  chroma:
    persist_dir: ${CHROMA_DIR:./chroma}

# llm:
#   provider: openai.azure
#   embedding_model: text-embedding-3-large
#   chat_model: gpt-4o-mini
#   params:
#     api_base: ${OPENAI_API_BASE}
#     api_key: ${OPENAI_API_KEY}
#     api_version: ${OPENAI_API_VERSION}
#     embedding_deployment: ${EMBEDDING_DEPLOYMENT:-text-embedding-3-large}
#     chat_deployment: ${CHAT_DEPLOYMENT:-gpt-4o-mini}
llm:
  provider: ${LLM_PROVIDER:openai} # openai | azure
  openai:
    api_key: ${OPENAI_API_KEY:}
    api_base: ${OPENAI_API_BASE:https://api.openai.com/v1}
    chat_model: ${OPENAI_CHAT_MODEL:gpt-4o-mini}
    embed_model: ${OPENAI_EMBED_MODEL:text-embedding-3-small}
  azure:
    api_key: ${AZURE_OPENAI_API_KEY:}
    endpoint: ${AZURE_OPENAI_ENDPOINT:}
    api_version: ${AZURE_OPENAI_API_VERSION:2024-06-01}
    chat_deployment: ${AZURE_OPENAI_CHAT_DEPLOYMENT:gpt-4o-mini}
    embed_deployment: ${AZURE_OPENAI_EMBED_DEPLOYMENT:text-embedding-3-small}

# ocr:
#   enabled: true
#   engine: tesseract
#   languages: ["eng","fra","ara"]
#   min_confidence: 0.4
ocr:
  enabled: false
  provider: tesseract # ou "none"
  languages: ['eng', 'fra', 'ara']
  tesseract_cmd: ${TESSERACT_CMD:}

embedding:
  dim: 1536

# chunking:
#   strategy: tokens
#   tokens: 600
#   overlap: 80
#   normalize_whitespace: true
chunk:
  strategy: simple
  size: 800
  overlap: 150

pipelines:
  end_to_end:
    steps: [import, extract, chunk, embed, kg]

storage:
  root: ./data/series
  tmp_dir: ./data/tmp
  allowed_extensions: [".pdf",".txt",".csv",".docx",".xlsx",".xls"]
