# config/settings.yaml

# app:
#   env: dev
#   host: 127.0.0.1
#   port: 8050
#   dev_reload: true
app:
  name: ${APP_NAME:rs-rraPhrag}
  env: ${APP_ENV:dev}
  host: ${HOST:127.0.0.1}
  port: ${PORT:8050}
  log_level: ${LOG_LEVEL:INFO}

storage:
  # backend: local
  root: ${STORAGE_ROOT:./data}
  series_dirname: series
  tmp_dir: ${STORAGE_TMP:./data/_tmp}
  allowed_extensions: ['.pdf', '.txt', '.csv', '.docx', '.xlsx', '.xls'] # Extensions autorisées pour l'import multi-fichiers
  max_file_size_mb: 64

upload:
  max_size_mb: 50

neo4j:
  uri: ${NEO4J_URI:bolt://localhost:7687}
  database: ${NEO4J_DATABASE:neo4j}
  username: ${NEO4J_USERNAME:neo4j}
  password: ${NEO4J_PASSWORD:neo4j}
  timeout: 15

vector:
  provider: chroma
  chroma:
    persist_dir: ${CHROMA_DIR:./chroma}
  type: memory
  
llm:
  provider: ${LLM_PROVIDER:openai} # openai | azure
  openai:
    api_key: ${OPENAI_API_KEY:}
    api_base: ${OPENAI_API_BASE:https://api.openai.com/v1}
    chat_model: ${OPENAI_CHAT_MODEL:gpt-4o-mini}
    embed_model: ${OPENAI_EMBED_MODEL:text-embedding-3-small}
  azure:
    api_key: ${AZURE_OPENAI_API_KEY:}
    endpoint: ${AZURE_OPENAI_ENDPOINT:}
    api_version: ${AZURE_OPENAI_API_VERSION:2024-06-01}
    chat_deployment: ${AZURE_OPENAI_CHAT_DEPLOYMENT:gpt-4o-mini}
    embed_deployment: ${AZURE_OPENAI_EMBED_DEPLOYMENT:text-embedding-3-small}
  embedder:
    provider: ${EMBEDDER_PROVIDER:openai_azure}
    model: ${EMBEDDER_MODEL:text-embedding-3-large}
    api_base: ${OPENAI_API_BASE:}
    api_key: ${OPENAI_API_KEY:}
    api_version: ${OPENAI_API_VERSION:2024-02-15-preview}
    dim: 0   # 0 => auto

ocr:
  enabled: false
  provider: tesseract # ou "none"
  languages: ['eng', 'fra', 'ara']
  tesseract_cmd: ${TESSERACT_CMD:}
  # min_confidence: 0.4

embedding:
  dim: 1536

chunk:
  strategy: simple # tokens
  size: 800
  overlap: 150
  # normalize_whitespace: true

pipelines:
  end_to_end:
    steps: [import, extract, chunk, embed, kg]

storage:
  root: ./data/series
  tmp_dir: ./data/tmp
  allowed_extensions: [".pdf",".txt",".csv",".docx",".xlsx",".xls"]
