# config/settings.yaml

app:
  name: ${APP_NAME:rs-rraPhrag}
  env: ${APP_ENV:dev}
  host: ${HOST:127.0.0.1}
  port: ${PORT:8050}
  port_snd: ${PORT_SND:8443}
  log_level: ${LOG_LEVEL:INFO}
  # dev_reload: ${DEV_RELOAD:false}

storage:
  root: ${STORAGE_ROOT:./data}
  tmp_dir: ${STORAGE_TMP:./data/_tmp}
  series_dirname: ${STORAGE_SERIES_DIRNAME:series}
  # allowed_extensions: ${STORAGE_ALLOWED_EXTENSIONS}
  allowed_extensions: ['.pdf', '.txt', '.csv', '.docx', '.xlsx', '.xls']
  max_file_size_mb: ${STORAGE_MAX_FILE_SIZE_MB:64}

neo4j:
  uri: ${NEO4J_URI:bolt://localhost:7687}
  database: ${NEO4J_DATABASE:neo4j}
  username: ${NEO4J_USERNAME:neo4j}
  password: ${NEO4J_PASSWORD:neo4j}
  connection_timeout: ${NEO4J_TIMEOUT:15.0}
  max_connection_lifetime: ${NEO4J_MAX_CONNECTION_LIFETIME:3600}
  max_transaction_retry_time: ${NEO4J_MAX_TRANSACTION_RETRY_TIME:10.0}

vector:
  provider: ${VECTOR_PROVIDER:chroma}
  type: ${VECTOR_TYPE:memory}
  chroma:
    persist_dir: ${VECTOR_CHROMA_PERSIST_DIR:./chroma}

provider:
  openai:
    api_key: ${OPENAI_API_KEY}
  #   api_base: ${OPENAI_API_BASE:https://api.openai.com/v1}
    chat_model: ${OPENAI_CHAT_MODEL:gpt-4o-mini}
    embed_model: ${OPENAI_EMBED_MODEL:text-embedding-3-small}
    dim: ${OPENAI_DIM:1024}
  azure:
    api_key: ${AZURE_OPENAI_API_KEY}
    api_version: ${OPENAI_API_VERSION}
    azure_endpoint: ${OPENAI_API_BASE}
    dep_name: ${DEPLOYMENT_NAME}
    embed_dep: ${AZURE_EMBED_DEP}
    dim: ${AZURE_DIM:1024}
  gemini:
    api_key: ${GOOGLE_API_KEY}
    chat_model: ${GOOGLE_CHAT_MODEL}
    embed_model: ${GOOGLE_EMBED_MODEL}
    dim: ${GEMINI_DIM:1024}
  phi:
    model_name: ${PHI_MODEL_NAME}
    embed_model_name: ${SENTENCE_TRANSFORMERS_MODEL}
  default: ${DEFAULT_PROVIDER:azure} # openai | azure | gemini
  

ocr:
  enabled: true
  provider: tesseract # ou "none"
  languages: ['eng', 'fra', 'ara']
  tesseract_cmd: ${TESSERACT_CMD}
  tessdata_prefix: ${TESSDATA_PREFIX}
  # min_confidence: 0.4

chunk:
  strategy: simple # tokens
  size: 800
  overlap: 150
  # normalize_whitespace: true

pipelines:
  end_to_end:
    steps: [import, extract, chunk, embed, kg]